service: mtglm-matches

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  memorySize: 128
  environment:
    ALLOWED_ORIGIN: ${env:ALLOWED_ORIGIN}
    MATCH_TABLE_NAME:
      Fn::ImportValue: ${self:provider.stage}-mtglm-MatchTableName
    RECORD_TABLE_NAME:
      Fn::ImportValue: ${self:provider.stage}-mtglm-RecordTableName
    PLAYER_TABLE_NAME:
      Fn::ImportValue: ${self:provider.stage}-mtglm-PlayerTableName
    SEASON_METADATA_TABLE_NAME:
      Fn::ImportValue: ${self:provider.stage}-mtglm-SeasonMetadataTableName
    USER_POOL_ID:
      Fn::ImportValue: ${self:provider.stage}-mtglm-UserPoolId

package:
  include:
    - ../build/**
    - ../node_modules/**

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-aws-documentation

resources:
  Resources:
    MatchesApiGatewayAuthorizer: ${file(partials/apiGatewayAuthorizer.yml)}

custom:
  documentation: ${file(partials/documentation.yml)}
  userPoolArn:
    Fn::ImportValue: ${self:provider.stage}-mtglm-UserPoolArn
  userPoolName:
    Fn::ImportValue: ${self:provider.stage}-mtglm-UserPoolName
  matchTableArn:
    Fn::ImportValue: ${self:provider.stage}-mtglm-MatchTableArn
  recordTableArn:
    Fn::ImportValue: ${self:provider.stage}-mtglm-RecordTableArn
  playerTableArn:
    Fn::ImportValue: ${self:provider.stage}-mtglm-PlayerTableArn
  SeasonMetadataTableArn:
    Fn::ImportValue: ${self:provider.stage}-mtglm-SeasonMetadataTableArn

functions:
  Get: ${file(partials/functions/get.yml)}
  Create: ${file(partials/functions/create.yml)}
  Delete: ${file(partials/functions/delete.yml)}
